### ISSUE TITLE
instrument sometimes breaks at triplet

### ISSUE THREAD

**Issue by remcohh** [cuthbertLab/music21j#10]
I noticed something strange:
using this script:
function renderTune(options){
    require(['music21'], function () {
        var s1 = music21.tinyNotation.TinyNotation(options.notation);
        var s = new music21.stream.Score();
        s.insert(0, s1);
        s.tempo = options.tempo;
        lsf('xylophone', function(i) {
            s1.instrument = i;
            s.renderScrollableCanvas($("#score"))
        })
    })
};

I render this tinynotation: "4/4 a b c d e b a b trip{c d e} a b "

Most of the time this goes well but now and then the instrument "xylophone" returns to the default "piano" sound and the strange thing is: this happens always at the third note of the triplet
I don't have a clue what is happening there

**Comment by mscuthbert** [comment]
If still a problem with recent builds, please feel free to reopen.
