### ISSUE TITLE
Pitches appear in wrong octave after initial 8vb clef

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21j#100]
```diff
--- a/testHTML/musicxmlTest.html
+++ b/testHTML/musicxmlTest.html
@@ -8,7 +8,7 @@
 
     <script src="../build/music21.debug.js"></script>
     <script>
-    mxUrl = 'bachOut.xml';
+    mxUrl = 'https://raw.githubusercontent.com/cuthbertLab/music21/master/music21/corpus/trecento/PMFC_13_19-Credo Scabroso.xml';
     sp = new music21.musicxml.xmlToM21.ScoreParser();
     sp.scoreFromUrl(mxUrl).done(() => {
         sc = sp.stream;
```

These tied notes should be unisons and continue in same register:

![Screen Shot 2021-05-16 at 4 17 06 PM](https://user-images.githubusercontent.com/38668450/118411369-2fcdd180-b662-11eb-8a08-e34c22d39789.png)

**Comment by mscuthbert** [comment]
The clef must be appearing in a place where the "getContextByClass" is not reading it?

**Comment by mscuthbert** [comment]
The whole `.clef` `.keySignature` and `.timeSignature` system in J is a mess -- it began with a far simpler system than music21p and then evolved to support most of 21p's context system, but the old crutches are still around and gumming up the system.

**Comment by jacobtylerwalls** [comment]
The default TrebleClef is inserted into the part's elements at the end of part parsing:

https://github.com/cuthbertLab/music21j/blob/0fd91fab04c182228de5f1751bc8c67258f43358/src/musicxml/xmlToM21.ts#L197

There's commented out code for getting the actual clef:

https://github.com/cuthbertLab/music21j/blob/0fd91fab04c182228de5f1751bc8c67258f43358/src/musicxml/xmlToM21.ts#L755-L757

Then, finding no clef in m.2, we will check the part site, and find that defaulted TrebleClef at the first position:

https://github.com/cuthbertLab/music21j/blob/0fd91fab04c182228de5f1751bc8c67258f43358/src/stream.ts#L525-L532

***

Solution for now to just restore the commented out block?
