### ISSUE TITLE
Uncaught TypeError: Cannot read property 'py/id' of null

### ISSUE THREAD

**Issue by ubaldino** [cuthbertLab/music21j#12]
I want to generate a json file in the following example
http://web.mit.edu/music21/doc/moduleReference/moduleVexflowToMusic21j.html

to tranportarlo to music21j the following example
https://github.com/cuthbertLab/music21j/blob/master/testHTML/jsonpickleParse.html

but when testing throws the following error in the console browser
"Uncaught TypeError: Cannot read property 'py/id' of null"

**Comment by mscuthbert** [comment]
Dupe of #13 perhaps?  Yours was first, but I think that that one gives more details.  Re-open if it's not.
