### ISSUE TITLE
p.step undefined when using editableAccidentalCanvas()

### ISSUE THREAD

**Issue by mlorenzon** [cuthbertLab/music21j#14]
I was receiving the error message "p.step is undefined" when using the editableAccidentalCanvas examples. I found that commenting out lines 1497–1500 of stream.js, in noteChanged, solved the problem. But maybe this code is there for other reasons.

```
    p = new pitch.Pitch("C");
    p.diatonicNoteNum = clickedDiatonicNoteNum;
    p.accidental = n.pitch.accidental;
    n.pitch = p;
```

Matthew

**Comment by mscuthbert** [comment]
returning to m21j after a year away.  Will be on it soon.

**Comment by mscuthbert** [comment]
I think that recent changes have fixed this.  If they haven't can you send a whole test case to see.  Thanks!
