### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by ronyeh** [cuthbertLab/music21j#142]
https://github.com/cuthbertLab/music21j/blob/c8afb21a12e52c505ccef772441a3c7282a65bbe/src/vfShow.ts#L654

I'm currently migrating music21j to VexFlow 4. Pretty straightforward so far!

Vex.Flow.Staves (plural)... is that a typo?

**Comment by mscuthbert** [comment]
Yes.  Should just be Stave.  Will fix in the v4 PR.  Since we're not getting typing from Vexflow at this point it doesn't really matter.

**Comment by ronyeh** [comment]
I fixed this in PR #172 

https://github.com/cuthbertLab/music21j/pull/172/files#diff-4de1d0b7045e52249da4efd9a77bcb9aaa18a906759d0e0f641ccd8b120253d0R702-R705
