### ISSUE TITLE
stave.glyph_start_x

### ISSUE THREAD

**Issue by ronyeh** [cuthbertLab/music21j#143]
https://github.com/cuthbertLab/music21j/blob/c8afb21a12e52c505ccef772441a3c7282a65bbe/src/vfShow.ts#L1144

https://unpkg.com/browse/vexflow@1.2.90/src/stave.js

I can't find this instance variable in version 1.2.90 (or 3.0.9). We also don't have it in VexFlow 4.

**Comment by mscuthbert** [comment]
strange -- that must have disappeared in the v0 to v1 Vexflow migration -- you know...this might explain some things, since 10 + undefined = NaN.  

Well, that's why we're switching everything to typescript!

**Comment by ronyeh** [comment]
I see, the last time it existed was in https://unpkg.com/browse/vexflow@1.2.36/src/stave.js

In 1.2.38, it was renamed to start_x: https://unpkg.com/browse/vexflow@1.2.38/src/stave.js

So you can probably just delete the second part, and set noteOffsetLeft to stave.start_x.

**Comment by mscuthbert** [comment]
Fixed in #196
