### ISSUE TITLE
Help getting music21j to work

### ISSUE THREAD

**Issue by NaldoM** [cuthbertLab/music21j#17]
I've tried running a couple of the examples, the forms render but the rest is blank, I can't see any notes or play music. i get the following error when I try running the layout.html example using the provided python server:

`python start_python_server.py 
Beginning HTTP/CGI server at 8000
127.0.0.1 - - [24/Jul/2016 00:47:44] "GET /testHTML/layout.html HTTP/1.1" 200 -
127.0.0.1 - - [24/Jul/2016 00:47:45] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 00:47:45] "GET /src/ext/jsonpickle/main.js HTTP/1.1" 404 -
127.0.0.1 - - [24/Jul/2016 00:47:45] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 00:47:45] "GET /src/ext/midijs/inc/shim/Base64binary.js HTTP/1.1" 404 -
127.0.0.1 - - [24/Jul/2016 00:47:45] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 00:47:45] "GET /src/ext/midijs/inc/shim/WebAudioAPI.js HTTP/1.1" 404 -
127.0.0.1 - - [24/Jul/2016 00:47:45] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 00:47:45] "GET /src/ext/midijs/inc/jasmid/midifile.js HTTP/1.1" 404 -
127.0.0.1 - - [24/Jul/2016 00:47:45] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 00:47:45] "GET /src/ext/midijs/inc/jasmid/replayer.js HTTP/1.1" 404 -
127.0.0.1 - - [24/Jul/2016 00:47:45] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 00:47:45] "GET /src/ext/midijs/inc/jasmid/stream.js HTTP/1.1" 404 -
127.0.0.1 - - [24/Jul/2016 00:47:45] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 00:47:45] "GET /src/ext/midijs/examples/inc/event.js HTTP/1.1" 404 -
`

**Comment by mscuthbert** [comment]
Make sure that you've pulled in the subprojects. It should be in the README. Or run updateGit I believe.

**Comment by NaldoM** [comment]
I downloaded and installed npm-git-update (couldn't find updateGit) but it isn't working correctly for me. I'll just have to do it manually but I'm not quite sure where to put the dependencies so that music21j can find them. I don't get any errors running npm-install though 

Thanks for the help

**Comment by NaldoM** [comment]
Actually I realised I just had to run npm update git
I also ran npm-install afterwards, but it didn't fix the issue

**Comment by remon-georgy** [comment]
I guess what @mscuthbert meant is to update git submodules. Following commands were enough to get all demos under http://localhost:8000/testHTML/ to work properly:

```
cd [music21j-root]
git submodule init && git submodule update
python start_python_server.py
Then head to http://localhost:8000/testHTML/ and check few demos.
```
Hope that helps.

**Comment by NaldoM** [comment]
thanks! I got it to work
