### ISSUE TITLE
Cant make it work on Apache

### ISSUE THREAD

**Issue by batata004** [cuthbertLab/music21j#223]
Hi,

I copied all the files to my webserver (Apache 2.4 latest) and tried to run all demos, and all of them show an error message. For example, when accessing:

http://localhost/music21j-master/testHTML/delayMic.html

It shows the error message:

`delayMic.html:28 Uncaught ReferenceError: music21 is not defined`

This is the same error on all demos. What I am doing wrong?

**Comment by jacobtylerwalls** [comment]
Did you also copy the javascript bundle referenced here?
https://github.com/cuthbertLab/music21j/blob/6188b0578d39a90abdf8c91ec3d795e56838f97e/testHTML/delayMic.html#L3

**Comment by jacobtylerwalls** [comment]
See the README files in the main directory and the build directory for information on producing a frontend asset bundle. Feel free to make use of resources on the internet for understanding `npm` commands also.
