### ISSUE TITLE
Enharmonics methods in pitches.js can end up in infinite while loop

### ISSUE THREAD

**Issue by ryaanahmed** [cuthbertLab/music21j#24]
Seems to occur when passing in a double flat—possibly also double sharp.

**Comment by mscuthbert** [comment]
I can't replicate this -- can you give an example of such a note?

**Comment by ryaanahmed** [comment]
Just tracked down the problem: it happens whenever the enharmonic that's being generated would require a quadruple accidental. e.g.,
```
const n = new music21.note.Note('E##3')
const enharmonic = n.pitch.getLowerEnharmonic()
```
 m21p.pitch.Accidental supports up to quadruple accidentals, m21j.pitch.Accidental only up to triple.

The actual problem in m21j.Pitch._getEnharmonicHelper() is:

```
while (p.ps % 12 !== this.ps % 12) { // octaveless
     p.accidental.alter += -1 * directionInt;
}
```

If abs(p.accidental.alter) is >= 3, this while loop goes into infinite loop, as the set() method on Accidental won't allow it to increment any further.

Any reason not to add quadruple sharp/flats to music21j? There's no actual bug in the enharmonics call if we do that.

**Comment by mscuthbert** [comment]
yes, and in any case, unsupported accidentals should raise an exception rather than silently passing.  m21p gives: `AccidentalException: -5 is not a supported accidental type`

**Comment by mscuthbert** [comment]
actually, it does in m21p also -- that's a problem.

**Comment by ryaanahmed** [comment]
Added quadruple accidentals via https://github.com/cuthbertLab/music21j/commit/1b2e5143050c62fad2f1f7ed20ad7c125fa9abea.

Throws a Music21Exception now if accName isn't supported.

n.b. Vexflow only supports triple sharps and flats, so we can now handle quadruple sharps and flats but can't actually show them. .vexflowModifier() throws an exception if we try to show a quad flat or sharp, anyway, so this should be easy to debug if anyone encounters it.
