### ISSUE TITLE
Adding music21j to external project

### ISSUE THREAD

**Issue by MRFaria** [cuthbertLab/music21j#27]
Hi,

I am not that great at javascript and am a bit confused on how to load the music21 project into my own project. What are the scripts exactly I need to include in my html page? Do I need to copy the whole 'src' and 'require' directories into my own project or is there a better way of doing this?

Thanks

**Comment by mscuthbert** [comment]
What sort of project are you building?  If you're talking about a set of static web pages or another javascript project, it's a bit different.  Thanks!

**Comment by MRFaria** [comment]
Ah yes, should have described better. I want to serve some html web pages that include some static js files using a python server.

**Comment by mscuthbert** [comment]
The easiest way to do so then is to copy the directory somewhere in your html folder, and either to use the example at http://web.mit.edu/music21/music21j/doc/index.html#toc1 (probably adding something like '/music21j/src' in place of '/src' and '/music21j/ext' for '/ext') or to reference '/music21j/build/music21.min' in place of '/src/music21' -- this will load everything and should work great.

**Comment by mscuthbert** [comment]
Music21j is now a single webpack file and npm module, making it easier to install in a website or into another project.
