### ISSUE TITLE
Tinynotation doesn't render just one bar

### ISSUE THREAD

**Issue by MRFaria** [cuthbertLab/music21j#28]
I've been playing around with the layout.html example and If I modify the code as follows to display just one bar on the stave then nothing is rendered:
```
        require(['music21'], function () { 
            s = new music21.stream.Score();
            p = music21.tinyNotation.TinyNotation('2/4 c2'); // or c4 c4
            s.append(p);
            s.appendNewDOM($("#scoreDiv"));
            ps = s.parts;
            ls = music21.layout.makeLayoutFromScore(s);
        });

```
If I then decide to add another half note to the p object then everything works as expected.

**Comment by mscuthbert** [comment]
known bug, but will raise the priority for fixing it.
