### ISSUE TITLE
testHTML/demo-DragScore.html

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21j#31]
When you drag a fragment to the $svgDiv, the fragment clearly registers – it plays back correctly and a bar is added to the new stave — but the stave is empty. This one replicates in Chrome, Firefox, Safari.

**Comment by mscuthbert** [comment]
Thanks!  Will look into it -- it's one of those demos that worked once, I figured out how it worked, used it in my own projects and then never went back to it.  Will see what changed.

**Comment by mscuthbert** [comment]
I think that this was fixed last summer?  Can you check if it's still a problem?  Thanks Mark!
