### ISSUE TITLE
testHTML/midiInChords.html

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21j#32]
Both the start and end of each note/chords register as starts. Could this be to do with one of the ‘noteOffs’ in src/music21/miditools.js?

This I can only produce in Chrome— the others don’t recognise the midi keyboards I've tried (which may speak to another problem … )

**Comment by mscuthbert** [comment]
Have you installed the Jazz Plugin (and in Safari also the Jazz-Extension)?  The other browsers keep making it harder to use MIDI.  I'll look more into the Chrome problem separately.

**Comment by mscuthbert** [comment]
I believe this is also fixed?
