### ISSUE TITLE
Importing music21j into Node

### ISSUE THREAD

**Issue by misterpilou** [cuthbertLab/music21j#33]
Hi, i'm referencing #27 as it is the same problem, i followed the instructions there. I also broke up my project pasing the night yesterday trying to import music21j. What i've done:

./my-project/music21j:
npm update
npm install

./my-project
npm install music21j

./my-project/main.js
import music21 from 'music21j'
page = new music21.Page()

and it's complaining about music21 being undefined

**Comment by mscuthbert** [comment]
I'm not really sure how to use Node here -- we're using es6-module imports and rollup, so it's really designed for now for web embedding.  Happy to take a PR that allows both, but right now that's the only way it works.

**Comment by misterpilou** [comment]
I would be glad to do so, my concern is about MIDI.js which seems to not be easily convert to a node package. I'm getting back to you

**Comment by misterpilou** [comment]
I see in stream.js that a comment that only MIDI.js is supported for playing playback. The other reference to MIDI.js is on keyboard/note/audiosearch and 2 others each calling noteOn which is also support by jazz-midi. So my guess is that the only need is to rewrite miditools.js using jazz-midi. Plus MIDI.js is unmaintained now on the contrary of jazz-midi. So i could do that for now. I don't have a very good insight of music21j for now, so i'm waiting for a confirmation from you

**Comment by mscuthbert** [comment]
I've made a npm version of MIDI.js called midicube (https://github.com/mscuthbert/midicube/) and it's working well -- almost done with making music21 work entirely with webpack; then it'll be in a position to start working on a node version (one that does not assume that Window is globalThis, etc.)

**Comment by misterpilou** [comment]
Hey, i will do it with great pleasure. I'll push it to npm as music21j v0.9.0. For me it will be well enough, or do you want a PR too?

**Comment by mscuthbert** [comment]
Hold off for a little bit: I published a new version on npm last night as v 9.7 but it doesn’t yet have the soundfonts working — they have to be downloaded post install. Once I get it stabilized on NPM for the browser then we can work on a node.js compatible version. Thanks for the push to do this!

**Comment by misterpilou** [comment]
What i've done: install vewflow, jquery and midicube from npm, i made a npm package for jsonpickle called jsonpickle-port and change the ref within the files. Then i publish my package by moving load-modules as the index for the package as of #27 . It seems to work however need to be tested more. The package name is music21j-port as you took music21j ans i didn't want to take music21 repo name.

**Comment by misterpilou** [comment]
i didn't test the soundfonts, i had work for now but i will try to do unit tests when i can

**Comment by mscuthbert** [comment]
Hi @misterpilou -- if you could it'd be better to unpublish it since this is basically the same things that I've been doing on the music21j branches, and it'd be really helpful to merge efforts there.  The webpack / npm / no-submodules version is now in as master, and it'd be great to start from there to getting to Node.js support.  Thanks!

**Comment by misterpilou** [comment]
I did it, if you accept my PR somehow i see no reasons to do otherwise

**Comment by mscuthbert** [comment]
I didn't see a PR here, can you explain more?

I changed the title here, since while npm install is done, I'm not sure the system runs under Node.js yet.

**Comment by misterpilou** [comment]
Ah, i meant in the future ^^'. Anyway, with your repo, i've got the following error:
Error: Cannot find module 'eslint-config-airbnb-base' however installing the following and eslint-plugin-import give me "m21basis is not defined". I've got this before, i've used babel plugins to bypass it

**Comment by mscuthbert** [comment]
Got it!

I've changed a lot of npm modules -- does deleting your node_modules and running "npm install" followed by "grunt webpack" fix it?  I haven't yet made webpack the default grunt yet.  Still a lot to do before 1.0!

**Comment by misterpilou** [comment]
Okay, it works just got a message about soundfounts.

**Comment by mscuthbert** [comment]
try running "npm postinstall"

**Comment by misterpilou** [comment]
It's maybe related to my project, i'm using electron. Anyway if you want to let some issues open for me to deal with them, i'm done.

**Comment by mscuthbert** [comment]
glad to take smaller or larger separate issues.  I don't know electron, but would like to learn.

**Comment by misterpilou** [comment]
I will play a bit with the API for now, i saw some of the code, what would you be thinking if i had some examples in the docs for now. I also think the layout was a really good idea. For electron, some of the doc in miditools or webmidi give me a hint, jazz plugin have a proper implementation for electron. I didn't understand how it was use in music21j (talking about the jazz plugin) but maybe it come from that
