### ISSUE TITLE
Issues when including `music21j` in my project

### ISSUE THREAD

**Issue by mttbernardini** [cuthbertLab/music21j#58]
Hello, I'm trying to use `music21j` in my project.

I'm a bit new to the node environment, but I figured out that using `webpack` was convenient for my purpose, so I created my project and then I run:

    npm install --save music21j

Then in one of my source files I tried:

    import { note } from "music21j"

But when I build the project using `npx webpack` I get various resolve errors like the following:

```
ERROR in ./node_modules/music21j/src/music21_modules.js
Module not found: Error: Can't resolve './music21/articulations' in '/home/matteo/git/nuvola/node_modules/music21j/src'
 @ ./node_modules/music21j/src/music21_modules.js 48:0-57 91:0-141:2
 @ ./src/core/melody/melody.js
 @ ./src/main.js
```

So I resorted to use the already built version provided (which however seems a bit of a hack to me, the above example should just work), by using

    import { note } from "music21j/releases/music21.debug"

I suspect that the issue might be related to the fact that the modules are written in typescript, but typescript doesn't get added to my dependencies nor get configured in the proper way. I don't know which is the proper way to handle this thing.

---

The second problem I'm facing is related with MIDI soundfonts. If I just build like in the above example I don't get any playback, and in the browser console I see the following error:

    Could not load soundfont; path was ../soundfonts/midi-js-soundfonts-master/FluidR3_GM//acoustic_grand_piano-ogg.js

The hack I found to make it work locally is to copy the files from `./node_modules/music21j/soundfonts` to `./dist/soundfonts` (I automated it using `copy-webpack-plugin`), but it doesn't work when I deploy to GitHub Pages (because of the level up `..` at the beginning of `../soundf....` and because I'm deploying a project page, so my base url is `mttbernardini.github.io/myproject`).

Is there a proper way to change the path of the soundfonts? I didn't find anything in the documentation and it seems to be hardcoded somewhere.

---

Let me know if you need more details, I'm willing to help.

Thank you in advance.

**Comment by mscuthbert** [comment]
try importing from 'music21' not 'music21j' -- for various reasons, music21j uses the same "music21" prefix as music21-python.

**Comment by mttbernardini** [comment]
```
ERROR in ./src/core/melody/melody.js
Module not found: Error: Can't resolve 'music21' in '/home/matteo/git/nuvola/src/core/melody'
 @ ./src/core/melody/melody.js 2:0-68 33:18-23 60:18-23 76:37-45 82:13-18 91:14-18 106:14-20 111:15-19
 @ ./src/main.js
```

I'm not sure about using `music21`, the `package.json` file clearly states that the name of the package is `music21j`. Am I missing something?

As for the second issue, I managed to fix it in the following way. Is it the way it should be done, though?

```
import { common } from "music21j/releases/music21.debug"
common.urls.soundfontUrl = "./soundfonts/midi-js-soundfonts-master/FluidR3_GM/"
```

Thank you again

**Comment by peterg98** [comment]
I have a similar issue when trying to using the converter. Except even when using the fix, I'm getting a bunch of `Cannot append *some Music21 Object* to Stream, Error: activeSite cannot be set for an object not in the stream`. Is this not suitable for web environments? For context I'm trying to use this with a Vue app.

**Comment by mscuthbert** [comment]
@peterg98 -- this sounds like a different issue.  Could you make a separate request?
