### ISSUE TITLE
Duration of pickup measures is the duration of a full measure

### ISSUE THREAD

**Issue by ryaanahmed** [cuthbertLab/music21j#67]
Not sure if this is a known issue (or perhaps also a music21 issue?):

Calling `duration()` on a Stream that contains, e.g., just 1 quarter note at offset 3.0 will give a Duration object with length 4.

This is because `Stream.duration()` constructs a new Duration object based on `Stream.highestTime()` -- the highest time is indeed 4 for this quarter note pickup stream, but seems to me that the duration should be 1.

Does this make sense @mscuthbert? Can patch in a fix if so.

**Comment by mscuthbert** [comment]
careful on changing this -- the calculation of Stream.duration is very performance critical, so anything that changes the duration of a Stream needs to be (a) very fast, and (b) not break much.

But why are pickup measures causing this problem at all?  In 4/4, a quarter pickup should still be at offset 0.0 -- to create a pickup, `Stream().paddingLeft = 3.0` should be used.

**Comment by ryaanahmed** [comment]
> But why are pickup measures causing this problem at all? In 4/4, a quarter pickup should still be at offset 0.0 -- to create a pickup, Stream().paddingLeft = 3.0 should be used.

Ah! In that case, I don't think there's actually a problem here. User error. Closing.
