### ISSUE TITLE
Will this be self 'rooting'

### ISSUE THREAD

**Issue by madtom1999** [cuthbertLab/music21j#8]
Currently this runs fine through the python web server but not through 'normal' web servers.
Will it be self rooting or will you need a 'rootdirectory.js' to allow you to publish stuff on 'normal' web sites?

**Comment by mlorenzon** [comment]
Hi, I'm having the same issue. It would be great to resolve it. Am I correct that you traced the problem to require.js?

All the best,
Matthew

**Comment by mscuthbert** [comment]
?? Can you explain what that means, mlorenzon? Just for other's help.

btw -- today's method will make the sample server work on Python 3.

**Comment by mscuthbert** [comment]
This issue seems to have several parts to it.  If there are still active issues in any part of it, please feel free to open new issues.  Thanks!
