### ISSUE TITLE
Importing music21j from CDN 

### ISSUE THREAD

**Issue by infojunkie** [cuthbertLab/music21j#88]
Hello,

I'm trying to import m21j on my web pages without building it locally. I [found it on jsDelivr](https://www.jsdelivr.com/package/npm/music21j) but I have some comments / questions:

- The module's main file at https://github.com/cuthbertLab/music21j/blob/master/package.json#L5 is `src/music21_modules.js` which confuses CDNs. It should probably refer to something in `releases`.
- The only release is `music21.debug.js` at 2.73MB. Would be great to have production, minified and gzipped files as well.
- When I import https://cdn.jsdelivr.net/npm/music21j@0.9.58/releases/music21.debug.js and embed a TinyNotation snippet, I see the following error in the console:
```
Could not load soundfont; path was https://cdn.jsdelivr.net/npm/music21j@0.9.58/soundfonts/midi-js-soundfonts-master/FluidR3_GM//acoustic_grand_piano-ogg.js
```
Is there a way to configure the URL of soundfonts? 

Thanks!

**Comment by mscuthbert** [comment]
See #60 -- I don't have a lot of experience in this, and I think at this point music21 v0.9 has been out there long enough that we can probably make the move.  There is a way to configure the soundfonts URL, with the m21conf variable, but it's also undocumented.

This is still alpha-level code, so help in making it better via PRs would be appreciated.  There's still so much to do!

**Comment by infojunkie** [comment]
Thanks. Closing this duplicate issue.
