### ISSUE TITLE
`scoreFromDOMTree()`: "No parts found in score"

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21j#97]
Pardon if user error, but I think parsing XML from a string (e.g. downloaded from a URL) isn't working. Known?

When I run:
```
import * as music21 from 'music21j';
var mxUrl = 'https://raw.githubusercontent.com/cuthbertLab/music21j/master/testHTML/bachOut.xml';
var sp = new music21.musicxml.xmlToM21.ScoreParser();
sp.scoreFromUrl(mxUrl).done(() => {
    var sc = sp.stream;
    sc.appendNewDOM();
});
```

I get:
"no parts found in score"

***

Here, when the jQuery result `$(xmlDoc)` is created, `<score-partwise>` is already in the result set, not among the children (which would be `<work>`, `<part-list>`, etc.):

https://github.com/cuthbertLab/music21j/blob/bef273db6233aba4d5da426dc3b2cd8b6608674f/src/musicxml/xmlToM21.ts#L81-L85

I can access `<score-partwise>` with either `[2]` or `.filter('score-partwise')[0]`:

![Screen Shot 2021-05-14 at 6 36 14 PM](https://user-images.githubusercontent.com/38668450/118338094-4ef22500-b4e3-11eb-80bd-52bb2555c927.png)

This was modeled off the Bach demo test in `testHTML/`, which is working, curiously! There, `xmlDoc` is a document object, not a string (perhaps because it was loaded from a local file and not requested over the web?)

**Comment by mscuthbert** [comment]
I think that this is a part of code that was never truly finished, so not surprised that it has errors, though I am surprised that the TestHTML code works and not this.
