### ISSUE TITLE
activeSite cannot be set for an object not in the stream

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21j#99]
I have a similar issue when trying to using the converter. Except even when using the fix, I'm getting a bunch of `Cannot append *some Music21 Object* to Stream, Error: activeSite cannot be set for an object not in the stream`. Is this not suitable for web environments? For context I'm trying to use this with a Vue app. I'm testing with xml files that do get parsed correctly in the Python version.

_Originally posted by @peterg98 in https://github.com/cuthbertLab/music21j/issues/58#issuecomment-652731308_

**Comment by jacobtylerwalls** [comment]
Can be reproduced like this:

```diff
--- a/testHTML/musicxmlTest.html
+++ b/testHTML/musicxmlTest.html
@@ -8,7 +8,7 @@
 
     <script src="../build/music21.debug.js"></script>
     <script>
-    mxUrl = 'bachOut.xml';
+    mxUrl = 'https://raw.githubusercontent.com/cuthbertLab/music21/master/music21/corpus/demos/two-parts.xml';
     sp = new music21.musicxml.xmlToM21.ScoreParser();
     sp.scoreFromUrl(mxUrl).done(() => {
         sc = sp.stream;

**Comment by jacobtylerwalls** [comment]
Call stack:

```
stream.ts:835 Cannot append element  Note {isProtoM21Object: true, isMusic21Object: true, _cloneCallbacks: {…}, _storedClasses: Array(6), _storedClassSet: Set(15), …}  to stream  Measure {isProtoM21Object: true, isMusic21Object: true, _cloneCallbacks: {…}, _storedClasses: Array(5), _storedClassSet: Set(12), …}  :  Error: activeSite cannot be set for an object not in the stream
    at new ExtendableError (exceptions21.ts:11)
    at new Music21Exception (exceptions21.ts:21)
    at new SitesException (sites.ts:20)
    at TrebleClef.set activeSite [as activeSite] (base.ts:147)
    at Measure.get (stream.ts:1128)
    at Measure.[Symbol.iterator] (stream.ts:305)
    at Generator.next (<anonymous>)
    at Measure.get highestTime [as highestTime] (stream.ts:337)
    at Measure.append (stream.ts:828)
    at MeasureParser.insertInMeasureOrVoice (xmlToM21.ts:381)
```

Failure is here:

https://github.com/cuthbertLab/music21j/blob/0fd91fab04c182228de5f1751bc8c67258f43358/src/stream.ts#L1163-L1167

Anticipated somewhat by this comment, so it's likely the clef/TS lookup that is problematic:

https://github.com/cuthbertLab/music21j/blob/0fd91fab04c182228de5f1751bc8c67258f43358/src/stream/filters.ts#L157-L164

**Comment by jacobtylerwalls** [comment]
brief digging: deeper failure involves trying to replace a TrebleClef with a BassClef. `replace()` runs once to try to get rid of the TrebleClef but it's not good enough -- the `TrebleClef` is in the stream twice, so then failures happen when getting .highestTime later and iterating over all the elements and their active sites (which was cleared by `replace()`):

![Screen Shot 2021-05-16 at 4 01 25 PM](https://user-images.githubusercontent.com/38668450/118410945-12980380-b660-11eb-8d41-7fb107185cd5.png)

**Comment by mscuthbert** [comment]
It seems like the bigger problem then is not checking that an object is already in the stream before adding it?
